version: '3'
services:
  app:
    image: my_app
    build: ./app
    ports:
     - 3000:3000
    depends_on:
      - "mongo"
      - "redis"
  redis:
    image: "redis"
    ports:
      - 6379:6379
  mongo:
    image: 'mongo'
    ports:
      - 27017:27017